### ISSUE TITLE
Pipe does not work in the test

### ISSUE THREAD

**Issue by roderik** [sstephenson/bats#10]
Hello,

after seeing the screencast by @drnic i'm trying out bats in test-kitchen. But 'im having trouble with the most basic test

```
#!/usr/bin/env bats

@test "Test if GitHub is in the global ssh_known_hosts file" {
    run cat /etc/ssh/ssh_known_hosts | grep github
    [ "$status" -eq 0 ]
}
```

With | grep github -> failure
Without | grep github -> succes but this doesn't test what i want it to test
Running by hand exit value is 0

**Comment by LvChengbin** [comment]
To use `eval` might be a better option, such as `run eval echo "xx" | cmd`, so that you don't need to export variables to subshells.

**Comment by carlosonunez** [comment]
`run` is a command, so the contents from `run` will be piped into its right-hand side. Use shell redirection like this as a workaround:

```bash
@test "Use grep in BATS tests" {
  run grep -q "$item_to_find" <(command_to_run)
  [ "$status" -eq 0 ]
}
```
