### ISSUE TITLE
Is there any support for running same tests with different environment variables?

### ISSUE THREAD

**Issue by nathanleclaire** [sstephenson/bats#100]
Hi @mislav @sstephenson I was wondering if there is any support for running mostly the same tests with only a few environment variables changed.  For instance you can see that on our project we have https://github.com/docker/machine/blob/master/test/integration/driver-amazonec2.bats and https://github.com/docker/machine/blob/master/test/integration/driver-digitalocean.bats and https://github.com/docker/machine/blob/master/test/integration/driver-virtualbox.bats with many many copy-pasted tests where the only thing changing is the `$NAME` and `$DRIVER` environment variables.  We are testing mostly the same "interface" with several different "backends".

I was wondering how you would approach this and if it is not possible, whether there might be a way to add the feature to BATS so I could consider hacking on it myself.

Thank you!  And nice work ;)

**Comment by mislav** [comment]
That's a good question. My first approach would be to teach the testing script (the one that runs `bats`) is to run `bats test/my-driver-tests.bats` multiple times, each time setting different environment variables for the process. In other words, I would run the same test files multiple times, once for each permutation of environment variables, similar to Travis CI test matrix.

If spawning multiple processes is unacceptable to you, I think you might need to hack bats. Let us know how it goes.

**Comment by nathanleclaire** [comment]
Interesting - I'll try that approach and see if we run into any limitations - currently we run `bats test.bats` directly and don't have a wrapper script, so that might help alleviate the situation a bit.

**Comment by spinus** [comment]
+1 for this feature

**Comment by nathanleclaire** [comment]
We ended up solving this with a wrapper script : https://github.com/docker/machine/blob/master/test/integration/run-bats.sh We have some custom requirements around teardown / environment setup too, so it made sense for our use case.
