### ISSUE TITLE
Check if $output contains a particular string

### ISSUE THREAD

**Issue by DinisCruz** [sstephenson/bats#106]
Hi, I'm using bats to write tests for docker build images, and on the test bellow

```bats
@test "curl installed" { 
  run curl --version;  
  [ $(expr "$output" : ".*curl 7.37.1") -eq 11 ]    # works
  [ "$output" == *"curl 7.37.1"* ];                 # doesn't work
}
```

I was able to use the ```[ $(expr "$output" : ".*curl 7.37.1") -eq 11 ]   ``` to check that the curl version was 7.37.1, but that syntax fells too complex

Is there another way?

Maybe something like ```[ "$output" == *"curl 7.37.1"* ];  ``` ?(which doesn't work)

**Comment by sstephenson** [comment]
You don’t need `run` or `$output` here.

```bash
@test "curl installed" {
  curl --version | grep '7\.37\.1’
}
```

**Comment by DinisCruz** [comment]
@sstephenson version works great

for example:

``` bash
#!/usr/bin/env bats
. ./src/api-git.sh
. ./src/api-veracode.sh

@test "load API ok and call git version" {
  result="$(git_version)"  
  echo $result | grep 'git version'
}
```

**Comment by simbo1905** [comment]
We use double squares and double equality to do string contains: 

```
  # Output should be verbose:
  [[ "$output" == *"cleaning"* ]]
  [[ "$output" == *"$encrypted_filename"* ]]
```
