### ISSUE TITLE
Use `-z` instead of `-n` for testing existence.

### ISSUE THREAD

**Issue by envygeeks** [sstephenson/bats#115]
We always quote variables coming regardless of trust, which means when we do `--env="CI='$CI'"` in our Docker runs to test our Docker Helpers we still get taps output because `-n` will return true, `-z` will return false on both `CI=` and `CI=''`

**Comment by mislav** [comment]
I'm sorry, but `CI=` and `CI=''` are equivalent in bash, and `-n` and `-z` are perfect opposites with no functional differences that I'm aware of. Can you be more specific?

**Comment by envygeeks** [comment]
They are the same except when there is quirky behavior with -n, but we worked around it, so I'm not mithered to explain it.

**Comment by mislav** [comment]
I would be interested to learn about the quirky behavior of `-n`.
