### ISSUE TITLE
Multiple command's in single case, requiring separate output verify

### ISSUE THREAD

**Issue by askb** [sstephenson/bats#132]
In my bats script, I need to do something like the below, where the stdout/stderr returned from `cmd1` is dependent on the result of `cmd2`. Is is possible to have a separate `$output` place holders for the `stderr/stdout` if multiple commands are run within the same test case, looking for the correct line number in `lines[]` is not easy sometimes when cmd's give out multiple lines output ?  Sorry for asking if this is already available, I am unable to find this case in your documentation.  thanks

```
#!/usr/bin/env bats

@test "testing somecmd and othercmd" {
  result="$(somecmd)"
  [ "$result" -eq 0 ]
  [ "$output" == "verify string here" ]
  result="$(somecmd)"
  [ "$result" -eq 0 ]
  [ "$output" == "verify something else here" ]
}
```

**Comment by ztombol** [comment]
It's the [`run` helper][bats-run] that captures the output in `$output` and exit status in `$status`. Unless you use it, the `$output` and `$status` variables remain empty. These two variables always hold the output and exit status of the command executed by the most recent invocation of `run`.

```
#!/usr/bin/env bats

@test "testing cmd1 and cmd2" {
  # Test `cmd1'
  run cmd1
  [ "$status" -eq 0 ]
  [ "$output" == "verify string here" ]

  # Test `cmd2'
  run cmd2
  [ "$status" -eq 0 ]
  [ "$output" == "verify something else here" ]
}
```

[bats-run]: https://github.com/sstephenson/bats#run-test-other-commands

**Comment by askb** [comment]
@ztombol, thanks for the suggestions. I also see some undefined behaviour while using `|` with the commands. For instance the below does not work:

```
@test "none: rm ask user confirmation when -y is not provided 'echo y | machine rm ba'" {
  run machine create -d none --url none ba
  [ "$status" -eq 0 ]
  echo y | run machine rm ba
  [ "$status" -eq 0 ]
}
```

Just fyi, fn `machine` gets expanded to:
```
  function machine() {
     export PATH="$MACHINE_ROOT"/bin:$PATH
     "$MACHINE_ROOT"/bin/"$MACHINE_BIN_NAME" "$@"
}
```

I would have to do something like the following to get this command working ?
```
@test "none: rm ask user confirmation when -y is not provided 'echo y | machine rm ba'" {
  run machine create -d none --url none ba
  [ "$status" -eq 0 ]
  echo y | { run machine rm ba
  [ "$status" -eq 0 ]
  }
}
```
This is issue is not limited to the above command, it happens while using `grep` and `|`.

**Comment by ztombol** [comment]
Use a sub-shell when you need to use `run` on an expression that uses piping.

```
@test 'run: piping commands' {
  run bash -c 'cmd1 | cmd2'
  [ "$status" -eq 0 ]
  [ "$output" == 'output' ]
}
```

You can read about this undocumented quirk [here][bats-pipe].

In your example, however, you don't need to use `run`.

```
@test "none: rm ask user confirmation when -y is not provided 'echo y | machine rm ba'" {
  machine create -d none --url none ba
  echo y | machine rm ba
}
```

From the Readme:

> Test cases consist of standard shell commands. Bats makes use of Bash's errexit (set -e) option when running test cases. If every command in the test case exits with a 0 status code (success), the test passes. In this way, each line is an assertion of truth.

Now that we are at it. Here's [another undocumented quirk][bats-cond] regarding conditional expressions (`[[`) before you are bitten by it.

[bats-pipe]: https://github.com/sstephenson/bats/issues/10#issuecomment-37872035
[bats-cond]: https://github.com/sstephenson/bats/issues/49

**Comment by askb** [comment]
@ztombol thanks will try out and update. :)

**Comment by askb** [comment]
closing this issue now.
