### ISSUE TITLE
Should I add on wiki that bats is available via brew for OSX ?

### ISSUE THREAD

**Issue by neonsoftware** [sstephenson/bats#152]
Hi ! 

I needed bats on OSX, and I just found it on brew. 
Installed and worked like a charm. 
Should I add it on the wiki on https://github.com/sstephenson/bats/wiki/Install-Bats-Using-a-Package ? 

Thanks in advance, great work guys

**Comment by ztombol** [comment]
Hi, @neonsoftware! That would be great!

**Comment by neonsoftware** [comment]
Done. Have a great week-end @ztombol

**Comment by ztombol** [comment]
Cool! You too have a great weekend!
