### ISSUE TITLE
[Question] Is there any possible way to pass parameter to bats call?

### ISSUE THREAD

**Issue by ShahriyarR** [sstephenson/bats#204]
I want to pass say some parameter from command-line to be used in bats:

```
[root@centos7-base ~]# bats test.bats fff
bats: /root/fff does not exist
/usr/local/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")
```

**Comment by ShahriyarR** [comment]
@mislav Maybe you have some idea about this? :)

**Comment by nilamjyotigoswami** [comment]
@ShahriyarR 
We pass run-time argument using the following
<argument_name>='<argument_value>' bats --log script_name.bats
eg :
vm_type='Linux' bats --log vmcreate.bats
In the script , we can use the variable $vm_type

Hope it helps

**Comment by ShahriyarR** [comment]
Exactly, it works :)
Thanks for comment.
Closing now.
