### ISSUE TITLE
[Question] Automated Test Case for Prompting Case

### ISSUE THREAD

**Issue by salmanhasni** [sstephenson/bats#215]
I have binary let say abc(executable)
I execute this file as ./abc and there are bunch of commands like help, version, list, login, ask-question,
I can easily automate help, version, and list arguments as they immediate give me response, whereas login and ask-question they suppose the prompt username, password and question respectively. how can i automated them
e.g
`$./abc login
type username:`

**Comment by dimo414** [comment]
This doesn't really seem related to Bats in any way. How would you like your application to behave in a non-interactive shell? Perhaps add flag variants for these inputs? Or use [`expect`](https://linux.die.net/man/1/expect).

**Comment by salmanhasni** [comment]
@dimo414 Yes now i have used the expect, thanks
