### ISSUE TITLE
Logging capabilities

### ISSUE THREAD

**Issue by lzap** [sstephenson/bats#28]
Hello,

I am evaluating bats for running installation and end-to-end cli testing of our project. So far so good, but one issue I have is I would like to be able to inspect output of the installation steps.

I use normal `@test` taks to do installation steps. It looks like something is logged as `/tmp/bats.PID.out` and then deleted.

What I would like to have would be something like:
- `--verbose` option to watch the progress of all tests (output + stderr)
- combined output log file of all stdout/stderr output

I will be happy to contribute one or both features, as long as you are fine with that.

**Comment by aerickson** [comment]
Here's an evolution of https://github.com/sstephenson/bats/pull/50 that sends the output to the log also. 

https://github.com/aerickson/bats/commit/91d1fbba44cff53b5f20202ca92700d04565dfbb
