### ISSUE TITLE
Stubbing out functions

### ISSUE THREAD

**Issue by nherson** [sstephenson/bats#38]
I'm working on a small personal project and I am trying to stub out the call to `hostname` to always return the same thing (no matter the machine it is executed on).

Basically, in my test file I just redefine `hostname` to echo what I want, but when I actually run my code with `run`, that definition isn't seen and calls to `hostname` end up returning my machine's hostname.

Am I doing this incorrectly, or is this not supported?

**Comment by devmanhinton** [comment]
Seeing this a while later, this is awesome -- good call @mislav Thank you!

**Comment by bishopb** [comment]
A separate file in your path is not strictly required, @nherson. First, here's the system under test:

```bash
#!/bin/bash
hostname
```

Now, the test that makes your hostname a mock:

```bash
hostname() { echo 'mock-hostname'; }

@test 'it does not override the hostname command' {
    run "$BATS_TEST_DIRNAME"/example.bash
    [ 'dev-bishop-frontend2125' = $output ]
}

@test 'it overrides the hostname command' {
    export -f hostname # the secret sauce
    run "$BATS_TEST_DIRNAME"/example.bash
    [ 'mock-hostname' = $output ]
}
```

If your system under test needs elevated privileges, `sudo -E` will not pass the exported function (for reasons I have yet to explain). [You will need to use `su`](https://serverfault.com/a/177764/204816) or the separate file method.

If you had a ton of functions you needed to export, you might use `declare -pf` to get the list of all prior defined functions, then dump those into the startup script (`.bash_profile` for example).
