### ISSUE TITLE
Add debug output to result

### ISSUE THREAD

**Issue by sven** [sstephenson/bats#4]
Hi Sam,

I'm currently using bats but have no idea how to dig deeper in a test case when something goes wrong.

Example testcase:

``` bash
    @test "build documentation" {
        [ -d "doc_dir/" ]
        pushd doc_dir/
        [ -e "Makefile" ]
        make
        [ -e "documentation.pdf" ]
        popd
    }
```

So if any of the above fails, I only see that the test fails and need to debug the failing line by hand. In bash I can do a `set -x` to see the lines as they are executed. Is it possible to do something like this in bats?

Thanks
  Sven

**Comment by JohannesFKnauf** [comment]
Recently we wanted to conveniently enable debug out of the full output of run commands in tests. We did not find a really satisfying solution, but stumpled upon this issue immediately. So adding for all the lost souls with the same problem:

We worked around it by adding some debug code to the teardown() { } function, which has all necessary variables in scope.
