### ISSUE TITLE
reading from STDIN / defining variables

### ISSUE THREAD

**Issue by amagura** [sstephenson/bats#84]
Bats can't read from `stdin`, which makes it impossible to run a command with an isolated rcfile:

``` bash
#!/bin/bash
startdir="$(dirname "$0")"

bats <<EOF
@test "this better be true" {
  cmd --rcfile="$startdir"/rc # FIXME doesn't work
  [ 1 -eq 1 ]
}
EOF
```

Instead of reading from `STDIN`, bats prints out its help usage:

``` bash
bats <<EOF
@test
EOF
# OUTPUT:
Bats 0.4.0
Usage: bats [-c] [-p | -t] <test> [<test> ...]
```

A work around would be to allow users to specify variables that can be used globally within the bats file, however, bats should still probably be able to read from `stdin` regardless.

``` bash
bats -v startdir="$(dirname "$0")" test.bats
```

**Comment by talexand** [comment]
Is there a way to deliberately bring in an environment variable like `$MYVAR` into a test from the test file?
