### ISSUE TITLE
No easy way to get path of bats test.

### ISSUE THREAD

**Issue by winmutt** [sstephenson/bats#85]
I am migrating some existing tests I wrote in bash to bats. In my testing I am comparing results of an exec with known good results stored in a file in my spec dir. There seems to be no easy way to access the filename/path of the executing test within the test. Would it be possible to set this as an environment variable or make the original argv available in the tests?

**Comment by sstephenson** [comment]
From https://github.com/sstephenson/bats#special-variables -

"`$BATS_TEST_FILENAME` is the fully expanded path to the Bats test file."

**Comment by winmutt** [comment]
Wow thanks, sorry I overlooked that!

**Comment by sstephenson** [comment]
No problem!
