### ISSUE TITLE
Support for cross-shell testing?

### ISSUE THREAD

**Issue by smikes** [sstephenson/bats#91]
I'm investigating using `bats` instead of `urchin` for `nvm` (see issue https://github.com/creationix/nvm/issues/429 for context) but one thing that I don't see how to implement in `bats` is testing `nvm` in different shells -- zsh, etc.

I know that the project is called "**bash** automated testing system", so it may be a long shot, but -- is there any intention to support testing other shells?

**Comment by ELLIOTTCABLE** [comment]
:+1:. I'd even be willing to contribute development time, if this was a desired feature and there was willing help to get me up-to-speed on your codebase. Big `bats` fan, but I'm a zsh junkie; been considering forking to `zats`, but …

**Comment by mislav** [comment]
I'm pretty sure that @sstephenson is not interested in supporting other shells. The way we use bats in rbenv and ruby-build is that we call (bash) executables and inspect their output and exit status. The language in which the executables are implemented in is irrelevant.

In the same fashion, to test your zsh scripts, just make them executable and have them process command-line arguments. If your zsh scripts aren't meant to be executable, you can still create an executable just for testing and load your zsh scripts within it.

**Comment by smikes** [comment]
Thanks for the context.
